export const userJson = {
    UserId: "1",
    CompanyKey: "jhhusyjejhjehjd",
    UserKey: "jhdddhdhd",
    UserEmail: "usermail@gmail.com",
    Action: 1,
  };

export const dummyUser = [
  {
    "CompanyKey": "12",
    "UserCode": "8976",
    "FirstName": "Debox",
    "LastName": "Global",
    "Email": "debox@gmail.com",
    "Phone": "",
    "Mobile": "8825632658",
    "Password": "debox3066",
    "PIN": "450450",
    "Role": "1",
    "Street": "",
    "LanguageKnown": "Hindi",
    "TimeFormat": "2",
    "Profile": "2",
    "Destination": "1",
    "UsersDepartment": "2",
    "ReportingManager": "5",
    "UserType": "5",
    "UserLoginType": "5",
    "AddedBy": "2",
    "UpdatedBy":1
  },

  {
    Id: "1",
    CompanyKey:"",
    UserCode: "876",
    FirstName: "Sanaul",
    LastName: "Ansari",
    Email: "sanaulansari@gmail.com",
    Phone: "880998870",
    Mobile: "989899299",
    Pin: "123",
    Role: "767",
    Street: "Noida",
    Password: "itsmypass",
    LanguageKnown: "Hindi",
    TimeFormat: "Idian Standard",
    Profile: "jadkjf",
    Destination: "Noida",
    UserDepartment: "Agent",
    ReportingManager: "hjad",
    UserType: "djkad",
    UserLoginType: "jdkkad",
    Status: "InActive",
  },
  {
    Id: "2",
    CompanyKey:"",
    FirstName: "Satendra",
    LastName: "Gurjar",
    Email: "satendra@gmail.com",
    Pin: "123",
    Password: "itsmypass",
    UserCode: "876",
    Phone: "880998870",
    Mobile: "989899299",
    Street: "Noida",
    TimeFormat: "Idian Standard",
    LanguageKnown: "Hindi",
    Destination: "Noida",
    Role: "767",
    UserDepartment: "Agent",
    Profile: "jadkjf",
    ReportingManager: "hjad",
    UserType: "djkad",
    UserLoginType: "jdkkad",
    Status: "Active",
  },
  {
    Id: "3",
    CompanyKey:"",
    FirstName: "Akmal",
    LastName: "Ansari",
    Email: "akmalansari@gmail.com",
    Pin: "123",
    Password: "itsmypass",
    UserCode: "876",
    Phone: "880998870",
    Mobile: "989899299",
    Street: "Noida",
    TimeFormat: "Idian Standard",
    LanguageKnown: "Hindi",
    Destination: "Noida",
    Role: "767",
    UserDepartment: "Agent",
    Profile: "jadkjf",
    ReportingManager: "hjad",
    UserType: "djkad",
    UserLoginType: "jdkkad",
    Status: "InActive",
  },
  {
    Id: "4",
    CompanyKey:"",
    FirstName: "Prasang",
    LastName: "Kumar",
    Email: "prasangkumar@gmail.com",
    Pin: "123",
    Password: "itsmypass",
    UserCode: "876",
    Phone: "880998870",
    Mobile: "989899299",
    Street: "Noida",
    TimeFormat: "Idian Standard",
    LanguageKnown: "Hindi",
    Destination: "Noida",
    Role: "767",
    UserDepartment: "Agent",
    Profile: "jadkjf",
    ReportingManager: "hjad",
    UserType: "djkad",
    UserLoginType: "jdkkad",
    Status: "Active",
  },
];
