export const userJson = {
    UserId: "1",
    CompanyKey: "jhhusyjejhjehjd",
    UserKey: "jhdddhdhd",
    UserEmail: "usermail@gmail.com",
    Action: 1,
  };

export const dummyUser = [
  {
    Id: "1",
    CompanyKey:"",
    FirstName: "Sanaul",
    LastName: "Ansari",
    Email: "sanaulansari@gmail.com",
    Pin: "123",
    Password: "itsmypass",
    UserCode: "876",
    Phone: "880998870",
    Mobile: "989899299",
    Street: "Noida",
    TimeFormat: "Idian Standard",
    LanguageKnown: "Hindi",
    Destination: "Noida",
    Role: "767",
    UserDepartment: "Agent",
    Profile: "jadkjf",
    ReportingManager: "hjad",
    UserType: "djkad",
    UserLoginType: "jdkkad",
    Status: "InActive",
  },
  {
    Id: "2",
    CompanyKey:"",
    FirstName: "Satendra",
    LastName: "Gurjar",
    Email: "satendra@gmail.com",
    Pin: "123",
    Password: "itsmypass",
    UserCode: "876",
    Phone: "880998870",
    Mobile: "989899299",
    Street: "Noida",
    TimeFormat: "Idian Standard",
    LanguageKnown: "Hindi",
    Destination: "Noida",
    Role: "767",
    UserDepartment: "Agent",
    Profile: "jadkjf",
    ReportingManager: "hjad",
    UserType: "djkad",
    UserLoginType: "jdkkad",
    Status: "Active",
  },
  {
    Id: "3",
    CompanyKey:"",
    FirstName: "Akmal",
    LastName: "Ansari",
    Email: "akmalansari@gmail.com",
    Pin: "123",
    Password: "itsmypass",
    UserCode: "876",
    Phone: "880998870",
    Mobile: "989899299",
    Street: "Noida",
    TimeFormat: "Idian Standard",
    LanguageKnown: "Hindi",
    Destination: "Noida",
    Role: "767",
    UserDepartment: "Agent",
    Profile: "jadkjf",
    ReportingManager: "hjad",
    UserType: "djkad",
    UserLoginType: "jdkkad",
    Status: "InActive",
  },
  {
    Id: "4",
    CompanyKey:"",
    FirstName: "Prasang",
    LastName: "Kumar",
    Email: "prasangkumar@gmail.com",
    Pin: "123",
    Password: "itsmypass",
    UserCode: "876",
    Phone: "880998870",
    Mobile: "989899299",
    Street: "Noida",
    TimeFormat: "Idian Standard",
    LanguageKnown: "Hindi",
    Destination: "Noida",
    Role: "767",
    UserDepartment: "Agent",
    Profile: "jadkjf",
    ReportingManager: "hjad",
    UserType: "djkad",
    UserLoginType: "jdkkad",
    Status: "Active",
  },
];
