import * as yup from "yup";

export const inputInitialValue = {
  id: "",
  QueryId: "",
  FDCode: "",
  PackageCode: "",
  PackageName: "",
  ClientType: "",
  AgentId: "",
  LeadPax: "",
  Subject: "",
  AddEmail: "",
  AdditionalInfo: "",
  QueryType: "",
  TravelInfo: "",
  PaxType: "",
  Priority: "",
  TAT: "",
  TourType: "",
  LeadSource: "",
  LeadRefrenced: "",
  HotelPrefrence: "",
  HotelType: "",
  MealPlan: "",
  AddedBy: "",
  UpdatedBy: "",
  ValueAddededServices: {
    Flight: "No",
    Visa: "No",
    Insurance: "No",
    Train: "No",
    Transfer: "No",
  },
  TravelDate: {
    Type: "",
    FromDate: "",
    ToDate: "",
    TotalDays: "",
    SeasonType: "",
    SeasonYear: "",
  },
  PaxInfo: {
    Adult: "",
    Child: "",
    Infant: "",
  },
  RoomInfo: {
    Single: "",
    Double: "",
    Twin: "",
    Triple: "",
    ExtraBed: "",
  },
};

export const InputSchema = yup.object().shape({
//   id: yup.number().required("Please Enter Id"),
//   QueryId: yup.number().required("Please Enter Id"),
//   FDCode: yup.number().required('Please Enter FDCode'),
//   PackageCode: yup.number().required('Please Enter PackageCode'),
//   PackageName: yup.string().required('Please Enter Package Name'),
  ClientType: yup.string().required('Please Enter Client Type'),
//   AgentId: yup.number().required('Please Enter Agent Id'),
  LeadPax: yup.string().required('Please Enter Lead Pax'),
  Subject: yup.string().required('Please Enter Subject'),
  AddEmail: yup.string().email().required('Enter a Valid Email'),
  AdditionalInfo:yup.string().required('Pleae Add Additional Info'),
  QueryType: yup.string().required('Please Enter Query Type'),
  TravelInfo: yup.string().required('Please Enter Travel Information'),
  PaxType: yup.string().required('Please Enter Pax Type'),
  Priority: yup.string().required('Please Enter Priority'),
  TAT: yup.string().required('Please Enter TAT'),
  TourType: yup.string().required('Please Enter Tour Type'),
  LeadSource: yup.string().required('Please Enter Lead Source'),
  LeadRefrenced: yup.string().required('Please Enter Lead Refferenced'),
  HotelPrefrence: yup.string().required('Please Enter Hotel Prefrence'),
  HotelType: yup.string().required('Please Enter Hotel Type'),
  MealPlan: yup.string().required('Please Enter Meal Plan'),
//   AddedBy: yup.string().required('Please Enter Added By'),
//   UpdatedBy: yup.string().required('Please Enter Updated By'),
//ValueAddServices..
  TravelDate:yup.string().required(),
  PaxInfo:yup.string().required(),
  RoomInfo:yup.string().required(),
  TravelDate:yup.object().shape({
    Type:yup.string().required('Please Select Type'),
    FromDate:yup.string().required('Please Select From Date'),
    ToDate:yup.string().required('Please Select ToDate'),
    TotalDays:yup.string().required('Please Enter Total Days')
  }),
  PaxInfo:yup.object().shape({
    Adult:yup.string().required('Please Enter Adult'),
    Child:yup.string().required('Please Enter Child'),
    Infant:yup.string().required('Please Enter Infant')
  }),
  RoomInfo:yup.object().shape({
    Single:yup.string().required('Required'),
    Double:yup.string().required('Required'),
    Twin:yup.string().required('Required'),
    Triple:yup.string().required('Required'),
    ExtraBed:yup.string().required('Required'),
  })

});
